services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    environment:
      - FREE_ONLY=on
      - SERVER_COUNTRIES=
      - TZ=
      - UPDATER_PERIOD=
      - VPN_SERVICE_PROVIDER=
      - VPN_TYPE=
      #- STREAM_ONLY=on
      - WIREGUARD_PRIVATE_KEY=
      - DOT=off
    volumes:
      - /opt/docker/gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9080:9080 #QBitTorrent Web-UI
      - 6881:6881 #QBitTorrent
      - 6881:6881/udp #QBitTorrent
      - 9117:9117 #Jackett
      - 7878:7878 #Radarr
      - 8989:8989 #Sonarr
      - 8080:8080 #sabnzbd
      - 8090:8090 #sabnzbd-https
      - 9696:9696 #prowlarr
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on: 
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=9080
      - TORRENTING_PORT=6881
    volumes:
      - /opt/docker/Configs/qbittorrent/config:/config
      - /<path_to_data>/data:/data
    restart: unless-stopped  
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    depends_on: 
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/Configs/sabnzbd/config:/config
      - /<path_to_data>/data:/data
    restart: unless-stopped
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    depends_on: 
      - gluetun
    network_mode: container:gluetun
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Denver
    volumes:
      - /opt/docker/Configs/Radarr/config:/config
      - /<path_to_data>/data:/data
    restart: unless-stopped
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    depends_on: 
      - gluetun
    network_mode: container:gluetun
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Denver
    volumes:
      - /opt/docker/Configs/Sonarr/config:/config
      - /<path_to_data>/data:/data
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on: 
      - gluetun
    network_mode: container:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/Configs/Prowlarr/config:/config
    restart: unless-stopped
