---
version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=Europe/London
       ports:
            - 5055:5055
       volumes:
            - ./appdata/config:/app/config
       restart: unless-stopped
